pipeline{
	agent any
	
	tools {
		maven 'Maven'
	}
	
	stages{
		stage('Check-out'){
			steps{		
				git branch:"main" , url:"https://github.com/narasimhaa44/maventest.git"
			}
		}
		stage('build'){
			steps{
				dir('MymavenApp01'){	
			    sh "mvn clean install"
				}
			}
		}
		stage('test'){
			steps{
				dir('MymavenApp01'){
				sh "mvn test"
				}
			}
		}
		stage('Run'){
			steps{
				dir('MymavenApp01'){
				sh "java -jar target/MymavenApp01-1.0-SNAPSHOT.jar"
				}
			}
		}
	}
	post {
		success{
			echo "Succesful pipeline creation"
		}
		failure {
			echo "Bug Occured"
		}
	}
}
